name: apartment_management_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  line_awesome_flutter: ^2.0.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_core: ^2.22.0
  provider: ^6.1.1
  country_picker: ^2.0.23
  firebase_storage: ^11.5.3
  shared_preferences: ^2.2.2
  pinput: ^3.0.1
  animated_custom_dropdown: ^2.0.0
  image_picker: ^1.0.4
  html: ^0.15.4
  firebase_app_check: ^0.2.1+8
  toggle_switch: ^2.1.0
  multi_select_flutter: ^4.1.3
  intl: ^0.19.0
  firebase_messaging: ^14.9.1
  http: ^1.2.1
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/apartcom.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/apartcom_logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/kapıcı.png
    - images/apartcom.png
    - images/background.jpg
    - images/payment.png
    - images/çöpüm_var.png
    - images/çöpüm_yok.png
